<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-GQ2CO30" failures="1" tests="3" name="Create Customer API Test" time="3.192" errors="0" timestamp="29 Jun 2021 22:00:37 GMT">
  <testcase classname="com.w2a.APITestingFramework.testcases.CreateCustomerTest" name="validateCreateCustomerAPIWithInValidSecretKey" time="1.882">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.w2a.APITestingFramework.testcases.CreateCustomerTest.validateCreateCustomerAPIWithInValidSecretKey(CreateCustomerTest.java:41)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- validateCreateCustomerAPIWithInValidSecretKey -->
  <testcase classname="com.w2a.APITestingFramework.testcases.CreateCustomerTest" name="validateCreateCustomerAPIWithValidSecretKey" time="1.25"/>
  <testcase classname="com.w2a.APITestingFramework.testcases.CreateCustomerTest" name="validateCreateCustomerAPIWithValidSecretKey" time="1.251"/>
</testsuite> <!-- Create Customer API Test -->
