<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-GQ2CO30" ignored="0" name="Create Customer API Test" tests="3" failures="1" timestamp="17 May 2021 02:27:15 GMT" time="3.5" errors="0">
  <testcase name="validateCreateCustomerAPIWithInValidSecretKey" time="2.53" classname="com.w2a.APITestingFramework.testcases.CreateCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.w2a.APITestingFramework.testcases.CreateCustomerTest.validateCreateCustomerAPIWithInValidSecretKey(CreateCustomerTest.java:41)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- validateCreateCustomerAPIWithInValidSecretKey -->
  <testcase name="validateCreateCustomerAPIWithValidSecretKey" time="0.815" classname="com.w2a.APITestingFramework.testcases.CreateCustomerTest"/>
  <testcase name="validateCreateCustomerAPIWithValidSecretKey" time="0.907" classname="com.w2a.APITestingFramework.testcases.CreateCustomerTest"/>
</testsuite> <!-- Create Customer API Test -->
